<?php
$sectionName = isset($sectionName) ? (string) $sectionName : 'Section';
$scope = isset($scope) && $scope === 'personal' ? 'personal' : 'section';
?>
<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Generate Accomplishment Flipbook</title><link href="<?= base_url(); ?>assets/css/bootstrap.min.css" rel="stylesheet"><link href="<?= base_url(); ?>assets/css/icons.min.css" rel="stylesheet">
<style>
body{min-height:100vh;margin:0;background:radial-gradient(circle at top,#6874e5,#252b81 52%,#161944);font-family:Arial,sans-serif}.filter-shell{min-height:100vh;display:flex;align-items:center;justify-content:center;padding:24px}.filter-card{width:min(100%,610px);padding:34px;border-radius:22px;background:#fff;box-shadow:0 25px 70px rgba(4,7,37,.42)}.eyebrow{color:#4d56d8;font-weight:800;font-size:.76rem;letter-spacing:.1em;text-transform:uppercase}.filter-card h1{margin:9px 0;color:#24295b;font-size:1.8rem}.filter-card p{margin:0 0 27px;color:#6c7391;line-height:1.6}.filter-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:17px}.filter-field{display:flex;flex-direction:column;gap:7px;color:#353b61;font-size:.82rem;font-weight:700}.filter-field select,.filter-field input{padding:11px 12px;border:1px solid #dce0ef;border-radius:9px;color:#30365d;background:#fff;font:inherit}.filter-field--wide{grid-column:span 2}.actions{display:flex;justify-content:space-between;align-items:center;gap:15px;margin-top:28px}.back{color:#4d56d8;text-decoration:none;font-weight:700}.generate{border:0;border-radius:9px;padding:12px 18px;color:#fff;background:#3d45c7;font-weight:700;cursor:pointer}@media(max-width:520px){.filter-card{padding:25px}.filter-grid{grid-template-columns:1fr}.filter-field--wide{grid-column:span 1}.actions{align-items:stretch;flex-direction:column-reverse;text-align:center}}
</style></head><body><main class="filter-shell"><section class="filter-card"><div class="eyebrow">Accomplishment Report</div><h1>Generate Flipbook</h1><p>Choose the records to include in the full-screen Flipbook for <?= htmlspecialchars($sectionName,ENT_QUOTES,'UTF-8'); ?>.</p><form method="get" action="<?= base_url(); ?>Page/accomplishment_flipbook"><div class="filter-grid"><label class="filter-field filter-field--wide">Scope<select name="scope"><option value="section" <?= $scope==='section'?'selected':''; ?>>Section Accomplishments</option><option value="personal" <?= $scope==='personal'?'selected':''; ?>>Personal Accomplishments</option></select></label><label class="filter-field">Activity Date From<input name="dateFrom" type="date"></label><label class="filter-field">Activity Date To<input name="dateTo" type="date"></label></div><div class="actions"><a class="back" href="<?= base_url(); ?>Page/viewSecAccomplishments">Back to list</a><button class="generate" type="submit"><i class="mdi mdi-book-open-page-variant"></i> Open Full-screen Flipbook</button></div></form></section></main></body></html>
