<?php
$esc = function($value) { return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8'); };
$representativeName = trim((string) ($representativeName ?? '')) ?: 'Name not recorded';
$representativeTitle = trim((string) ($representativeTitle ?? '')) ?: 'Title / Position not recorded';
$schoolName = trim((string) ($schoolName ?? '')) ?: 'School name not recorded';
$schoolCity = trim((string) ($schoolCity ?? '')) ?: 'City not recorded';
?>
<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Data Privacy Compliance Declaration</title>
<link href="<?= base_url(); ?>assets/css/bootstrap.min.css" rel="stylesheet"><link href="<?= base_url(); ?>assets/css/icons.min.css" rel="stylesheet"><link href="<?= base_url(); ?>assets/css/app.min.css" rel="stylesheet">
<style>
body{background:#f3f5f7;color:#15191d;font-family:Arial,Helvetica,sans-serif}.declaration{width:min(900px,calc(100% - 48px));margin:34px auto;padding:62px;background:#fff;box-shadow:0 8px 28px rgba(0,0,0,.1)}h1{margin:0 0 38px;text-align:center;font-size:1.65rem;font-weight:800;letter-spacing:.04em}p,li{font-size:1.05rem;line-height:1.7;text-align:justify}.clauses{padding-left:24px}.clauses li{margin-bottom:18px}.signature{margin-top:52px;font-size:1.05rem;line-height:1.65}.actions{width:min(900px,calc(100% - 48px));margin:24px auto 0}@media print{@page{margin:.75in 1in}body{background:#fff!important;color:#000}.actions{display:none}.declaration{width:100%;margin:0;padding:0;box-shadow:none}h1{font-size:16pt}p,li,.signature{font-size:11.5pt}}
</style></head><body><div class="actions"><a class="btn btn-light" href="<?= base_url(); ?>Page/school_pbei_requirements">Back</a><button type="button" class="btn btn-primary ml-2" onclick="window.print()"><i class="mdi mdi-printer-outline mr-1"></i>Print</button></div>
<main class="declaration"><h1>DECLARATION OF DATA PRIVACY COMPLIANCE</h1>
<p>I, <strong><?= $esc($representativeName); ?></strong>, serving as the <strong><?= $esc($representativeTitle); ?></strong> of <strong><?= $esc($schoolName); ?></strong> (the “PBEI”), hereby declare and warrant the following in relation to the submission of documents for the application for Government Permit/Government Recognition:</p>
<ol class="clauses" type="a"><li><strong>Lawful Collection and Sharing:</strong> That the PBEI, acting as a Personal Information Controller (PIC), has lawfully collected the personal data and Sensitive Personal Information (SPI) of its personnel included in this application.</li><li><strong>Principle of Transparency:</strong> That the PBEI has fully informed its personnel that their personal data and SPI (including but not limited to educational records, government-issued IDs, and professional licenses) will be shared with and processed by the Department of Education (DepEd) for the specific purpose of school accreditation.</li><li><strong>Consent and Rights:</strong> That the PBEI has secured the necessary consent from its personnel for the sharing of their data with DepEd or has otherwise established a valid lawful basis for such disclosure under the Data Privacy Act of 2012. The PBEI has provided its personnel with the appropriate Privacy Notice detailing the categories of recipients, the purpose of data sharing, and their rights as data subjects.</li><li><strong>Accountability:</strong> I acknowledge that the PBEI remains jointly accountable for upholding the data privacy rights of our personnel regarding the data shared with DepEd. The PBEI agrees to hold DepEd free and harmless from any claims, damages, or liabilities arising from the PBEI’s failure to secure lawful basis or inform its personnel prior to the disclosure of their personal data.</li></ol>
<div class="signature">Signed this <?= $esc($declarationDate ?? date('F j, Y')); ?>, at <?= $esc($schoolCity); ?> City, Philippines.<br><br><br>________________________________________<br><?= $esc($representativeName); ?><br><?= $esc($representativeTitle); ?><br><?= $esc($schoolName); ?></div>
</main></body></html>
