<?php $esc = function($value){ return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8'); }; ?>
<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Issue / Concern Details</title><link href="<?= base_url(); ?>assets/css/bootstrap.min.css" rel="stylesheet"><link href="<?= base_url(); ?>assets/css/icons.min.css" rel="stylesheet"><style>
body{background:#eef1f7;color:#172033;font-family:Arial,sans-serif}.print-actions,.detail-sheet{width:min(900px,calc(100% - 40px));margin-left:auto;margin-right:auto}.print-actions{margin-top:24px;margin-bottom:14px}.detail-sheet{margin-bottom:32px;padding:42px 48px;background:#fff;box-shadow:0 12px 36px rgba(23,32,51,.12)}.document-heading{margin-bottom:26px;padding-bottom:16px;border-bottom:3px solid #272b8c}.document-heading p{margin:0 0 5px;color:#4b556c;font-size:.86rem}.document-heading h1{margin:0;color:#272b8c;font-size:1.55rem}.detail-row{display:grid;grid-template-columns:250px 1fr;border-bottom:1px solid #dce1ea}.detail-row:last-child{border-bottom:0}.detail-label{padding:15px 18px;background:#f5f7fc;color:#323b56;font-size:.78rem;font-weight:700;letter-spacing:.04em;text-transform:uppercase}.detail-value{padding:15px 18px;white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.55}.priority{display:inline-block;padding:4px 10px;border-radius:16px;background:#fff1d6;color:#8d5b11;font-weight:700}.signature{margin-top:48px;display:flex;justify-content:flex-end}.signature div{width:240px;text-align:center;font-size:.84rem}.signature-space{display:block;height:62px}@media(max-width:640px){.detail-sheet{padding:26px 20px}.detail-row{grid-template-columns:1fr}.detail-label{padding-bottom:7px}.detail-value{padding-top:7px}}@page{size:A4 portrait;margin:12mm}@media print{html,body{width:210mm;min-height:297mm}body{background:#fff;font-size:10.5pt}.print-actions{display:none}.detail-sheet{width:186mm;min-height:273mm;margin:0;padding:0;box-shadow:none}.document-heading{margin-bottom:16px;padding-bottom:10px}.document-heading h1{font-size:16pt}.detail-row{grid-template-columns:220px 1fr;break-insside:avoid;break-inside:avoid}.detail-label,.detail-value{padding:9px 12px}.detail-label{background:#f2f3f6!important;-webkit-print-color-adjust:exact;print-color-adjust:exact}.signature{margin-top:35px}}
</style></head><body>
<div class="print-actions"><a class="btn btn-light" href="<?= base_url(); ?>Page/section_head_issues_concerns?year=<?= urlencode((string)$record->applicable_year); ?>"><i class="mdi mdi-arrow-left"></i> Back to Register</a><button type="button" class="btn btn-primary ml-2" onclick="window.print()"><i class="mdi mdi-printer"></i> Print</button></div>
<main class="detail-sheet"><header class="document-heading"><p>Department of Education &mdash; Schools Division of Davao Oriental</p><p><?= $esc($sectionName); ?></p><h1>Issue / Concern Details</h1></header>
<section class="detail-row"><div class="detail-label">Applicable Year</div><div class="detail-value"><?= $esc($record->applicable_year); ?></div></section>
<section class="detail-row"><div class="detail-label">Issue / Concern</div><div class="detail-value"><?= $esc($record->issue_concern); ?></div></section>
<section class="detail-row"><div class="detail-label">Degree of Priority</div><div class="detail-value"><span class="priority"><?= $esc($record->degree_of_priority ?: 'Not set'); ?></span></div></section>
<section class="detail-row"><div class="detail-label">Probable Cause/s</div><div class="detail-value"><?= $esc($record->probable_causes ?: 'Not specified'); ?></div></section>
<section class="detail-row"><div class="detail-label">Affected Performance / Output Indicator/s</div><div class="detail-value"><?= $esc($record->affected_performance ?: 'Not specified'); ?></div></section>
<section class="detail-row"><div class="detail-label">TA Need (Organization or Performance)</div><div class="detail-value"><?= $esc($record->ta_need ?: 'Not specified'); ?></div></section>
<section class="detail-row"><div class="detail-label">TA Type</div><div class="detail-value"><?= $esc($record->ta_type ?: 'Not specified'); ?></div></section>
<div class="signature"><div>Prepared by<span class="signature-space"></span><strong><?= $esc($preparedBy); ?></strong><br><span>Section Head</span></div></div></main>
</body></html>
