<?php
$records = isset($records) && is_array($records) ? $records : array();
$years = isset($availableYears) && is_array($availableYears) ? $availableYears : array();
$esc = function($value){ return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8'); };
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <?php include('includes/page-title.php'); ?>
    <link href="<?= base_url(); ?>assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?= base_url(); ?>assets/css/icons.min.css" rel="stylesheet">
    <link href="<?= base_url(); ?>assets/css/app.min.css" rel="stylesheet">
    <link href="<?= base_url(); ?>assets/libs/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
    <style>
        body{background:#f4f7fb}.issues-hero{margin:20px 0 24px;padding:30px;border-radius:18px;color:#fff;background:linear-gradient(135deg,#272b8c,#565de8)}.issues-hero h2{margin:8px 0;color:#fff}.issues-hero p{margin:0;color:rgba(255,255,255,.84)}.issues-card{border:0;border-radius:16px;box-shadow:0 10px 30px rgba(32,43,100,.08)}.filter-bar{display:flex;align-items:center;gap:12px;margin-bottom:20px}.filter-bar label{margin:0;color:#4a536c;font-weight:700}.filter-bar select{width:150px}.issues-table{min-width:1200px}.issues-table th{border-top:0!important;background:#272b8c!important;color:#fff!important;font-size:.73rem;letter-spacing:.04em;text-align:center;text-transform:uppercase;vertical-align:middle}.issues-table td{vertical-align:top;white-space:pre-line}.issues-table td:first-child{font-weight:700;min-width:210px}.issues-table td:nth-child(3),.issues-table td:nth-child(4),.issues-table td:nth-child(5){min-width:210px;max-width:330px}.issue-detail-link{color:#272b8c;text-decoration:none}.issue-detail-link:hover{color:#565de8;text-decoration:underline}.priority{display:inline-block;padding:4px 9px;border-radius:20px;background:#fff1d6;color:#8d5b11;font-size:.78rem;font-weight:700}.action-buttons{display:flex;gap:6px;justify-content:center}.action-buttons .btn{border-radius:8px}.form-group label{font-weight:700;color:#414964}@media(max-width:767.98px){.issues-hero{padding:22px}.issues-card .card-body{padding:1rem}.filter-bar{align-items:flex-start;flex-direction:column}}
    </style>
</head>
<body>
<div id="wrapper">
    <?php include('includes/top-bar.php'); ?>
    <?php include('includes/sidebar.php'); ?>
    <div class="content-page"><div class="content"><main class="container-fluid">
        <section class="issues-hero"><div class="row align-items-center"><div class="col-md-8"><div class="text-uppercase font-weight-bold small">Section Head Workspace</div><h2>Issues / Concerns</h2><p><?= $esc($sectionName); ?> &mdash; record concerns and technical-assistance needs.</p></div><div class="col-md-4 text-md-right mt-3 mt-md-0"><button class="btn btn-light" type="button" data-toggle="modal" data-target="#issueModal" onclick="openIssueForm()"><i class="mdi mdi-plus"></i> Add Issue / Concern</button></div></div></section>
        <?php if($this->session->flashdata('success')): ?><div class="alert alert-success"><?= $esc($this->session->flashdata('success')); ?></div><?php endif; ?>
        <?php if($this->session->flashdata('danger')): ?><div class="alert alert-danger"><?= $esc($this->session->flashdata('danger')); ?></div><?php endif; ?>
        <section class="card issues-card"><div class="card-body">
            <div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="header-title mb-1">Issues and Concerns Register</h4><small class="text-muted">Select an issue or concern to see its full, print-ready details.</small></div><span class="badge badge-primary badge-pill px-3 py-2"><?= count($records); ?> record<?= count($records)===1?'':'s'; ?></span></div>
            <form class="filter-bar" method="get" action="<?= base_url(); ?>Page/section_head_issues_concerns"><label for="issuesYear">Applicable Year</label><select class="form-control" id="issuesYear" name="year" onchange="this.form.submit()"><option value="<?= date('Y'); ?>"<?= $selectedYear===date('Y')?' selected':''; ?>><?= date('Y'); ?></option><?php foreach($years as $year): $value=trim((string)$year->applicable_year); if($value!=='' && $value!==date('Y')): ?><option value="<?= $esc($value); ?>"<?= $selectedYear===$value?' selected':''; ?>><?= $esc($value); ?></option><?php endif; endforeach; ?></select></form>
            <div class="table-responsive"><table id="issuesTable" class="table table-hover issues-table w-100"><thead><tr><th>Issues/ Concern</th><th>Degree of Priority</th><th>Probable Cause/s</th><th>Affected Performance/<br>Output Indicator/s</th><th>TA Need (Organization or Performance)</th><th>TA Type</th><th>Actions</th></tr></thead><tbody>
            <?php foreach($records as $record): ?><tr>
                <td><a class="issue-detail-link" title="View full details and print" href="<?= base_url(); ?>Page/section_head_issues_concern_details/<?= (int)$record->id; ?>"><?= $esc($record->issue_concern); ?></a></td>
                <td><span class="priority"><?= $esc($record->degree_of_priority?:'Not set'); ?></span></td><td><?= $esc($record->probable_causes); ?></td><td><?= $esc($record->affected_performance); ?></td><td><?= $esc($record->ta_need); ?></td><td><?= $esc($record->ta_type); ?></td>
                <td><div class="action-buttons"><a class="btn btn-sm btn-outline-secondary" title="View and print details" href="<?= base_url(); ?>Page/section_head_issues_concern_details/<?= (int)$record->id; ?>"><i class="mdi mdi-printer"></i></a><button class="btn btn-sm btn-outline-primary" type="button" title="Edit" data-toggle="modal" data-target="#issueModal" onclick='openIssueForm(<?= json_encode($record, JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP|JSON_HEX_TAG); ?>)'><i class="mdi mdi-pencil"></i></button><form method="post" action="<?= base_url(); ?>Page/section_head_issues_concerns_delete" onsubmit="return confirm('Remove this issue or concern?');"><input type="hidden" name="id" value="<?= (int)$record->id; ?>"><button class="btn btn-sm btn-outline-danger" title="Delete" type="submit"><i class="mdi mdi-delete"></i></button></form></div></td>
            </tr><?php endforeach; ?>
            </tbody></table></div>
        </div></section>
    </main></div><?php include('includes/footer.php'); ?></div>
</div>
<div class="modal fade" id="issueModal"><div class="modal-dialog modal-lg modal-dialog-centered"><form class="modal-content" method="post" action="<?= base_url(); ?>Page/section_head_issues_concerns_save"><div class="modal-header"><h5 class="modal-title" id="issueModalTitle">Add Issue / Concern</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><input type="hidden" name="id" id="issueId"><div class="form-group"><label>Applicable Year</label><input class="form-control" type="number" min="2000" max="2100" name="applicable_year" id="applicableYear" value="<?= date('Y'); ?>"></div><div class="form-group"><label>Issues / Concern <span class="text-danger">*</span></label><textarea class="form-control" name="issue_concern" id="issueConcern" rows="3" required></textarea></div><div class="form-group"><label>Degree of Priority</label><select class="form-control" name="degree_of_priority" id="degreeOfPriority"><option value="">Select priority</option><option>High</option><option>Medium</option><option>Low</option></select></div><div class="form-group"><label>Probable Cause/s</label><textarea class="form-control" name="probable_causes" id="probableCauses" rows="3"></textarea></div><div class="form-group"><label>Affected Performance/Output Indicator/s</label><textarea class="form-control" name="affected_performance" id="affectedPerformance" rows="3"></textarea></div><div class="form-group"><label>TA Need (Organization or Performance)</label><select class="form-control" name="ta_need" id="taNeed"><option value="">Select TA need</option><option>Organization</option><option>Performance</option><option>Organization and Performance</option></select></div><div class="form-group mb-0"><label>TA Type</label><input class="form-control" name="ta_type" id="taType"></div></div><div class="modal-footer"><button class="btn btn-light" type="button" data-dismiss="modal">Cancel</button><button class="btn btn-primary" type="submit">Save</button></div></form></div></div>
<script src="<?= base_url(); ?>assets/js/vendor.min.js"></script><script src="<?= base_url(); ?>assets/js/app.min.js"></script><script src="<?= base_url(); ?>assets/libs/datatables/jquery.dataTables.min.js"></script><script src="<?= base_url(); ?>assets/libs/datatables/dataTables.bootstrap4.min.js"></script>
<script>function openIssueForm(item){item=item||{};document.getElementById('issueModalTitle').textContent=item.id?'Edit Issue / Concern':'Add Issue / Concern';document.getElementById('issueId').value=item.id||'';document.getElementById('applicableYear').value=item.applicable_year||new Date().getFullYear();document.getElementById('issueConcern').value=item.issue_concern||'';document.getElementById('degreeOfPriority').value=item.degree_of_priority||'';document.getElementById('probableCauses').value=item.probable_causes||'';document.getElementById('affectedPerformance').value=item.affected_performance||'';document.getElementById('taNeed').value=item.ta_need||'';document.getElementById('taType').value=item.ta_type||'';}$(function(){$('#issuesTable').DataTable({pageLength:25,order:[]});});</script>
</body></html>
