<?php
$esc = function ($value) { return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8'); };
$types = array('Strength', 'Weakness', 'Opportunity', 'Threat');
$styles = array('Strength' => 'success', 'Weakness' => 'warning', 'Opportunity' => 'info', 'Threat' => 'danger');
$grouped = array();
foreach ((array) $entries as $entry) {
    $date = $entry->effectivity_date ?: $entry->applicable_year . '-01-01';
    if (!isset($grouped[$date])) $grouped[$date] = array_fill_keys($types, array());
    if (isset($grouped[$date][$entry->swot_type])) $grouped[$date][$entry->swot_type][] = $entry;
}
?>
<!DOCTYPE html>
<html lang="en"><head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php include('includes/page-title.php'); ?>
    <link rel="shortcut icon" href="<?= base_url(); ?>assets/images/favicon.ico">
    <link href="<?= base_url(); ?>assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="<?= base_url(); ?>assets/css/icons.min.css" rel="stylesheet" type="text/css">
    <link href="<?= base_url(); ?>assets/css/app.min.css" rel="stylesheet" type="text/css">
    <style>
        body { background: #f4f6fb; } .swot-hero { margin:20px 0 24px; padding:28px 30px; border-radius:22px; color:#fff; background:linear-gradient(135deg,#272b8c,#5158d5); box-shadow:0 16px 35px rgba(39,43,140,.2); }
        .swot-hero h2 { color:#fff; margin:8px 0 4px; } .swot-hero p { margin:0; opacity:.85; } .swot-card { border:0; border-radius:14px; overflow:hidden; box-shadow:0 4px 16px rgba(31,41,55,.08); height:100%; }
        .swot-card .card-header { font-weight:700; } .swot-entry { border-left:4px solid #d4d8e5; padding:11px 12px; margin-bottom:10px; background:#fafbfe; border-radius:4px; white-space:pre-wrap; }
        .swot-entry:last-child { margin-bottom:0; } .entry-actions { float:right; margin-left:10px; } .entry-actions button { border:0; background:transparent; padding:0 3px; color:#687187; } .entry-actions .delete { color:#dc3545; }
        .add-form { border:0; border-radius:14px; box-shadow:0 4px 16px rgba(31,41,55,.08); } .required { color:#dc3545; }
    </style>
</head><body><div id="wrapper">
    <?php include('includes/top-bar.php'); ?><?php include('includes/sidebar.php'); ?>
    <div class="content-page"><div class="content"><div class="container-fluid">
        <div class="swot-hero"><div class="d-flex align-items-center justify-content-between flex-wrap"><div><small class="text-uppercase font-weight-bold">Quality Management System</small><h2>SWOT Analysis</h2><p><?= $esc($sectionName); ?> · Identify strengths, weaknesses, opportunities, and threats by effectivity.</p></div><div class="mt-3 mt-md-0"><a class="btn btn-outline-light mr-2" href="<?= base_url(); ?>Page/qms_report_settings"><i class="mdi mdi-cog"></i> Report Settings</a><a class="btn btn-light" target="_blank" href="<?= base_url(); ?>Page/swot_report?effectivity=<?= rawurlencode($selectedEffectivity); ?>"><i class="mdi mdi-printer"></i> Generate Report</a></div><form method="get" class="w-100 mt-3"><div class="form-row"><div class="col-md-3"><input class="form-control" name="year" value="<?= $esc($selectedYear); ?>" aria-label="Applicable year"></div><div class="col-md-4"><select class="form-control" name="effectivity"><option value="">All effectivities</option><?php foreach ((array)$availableEffectivities as $date): ?><option value="<?= $esc($date->effectivity_date); ?>" <?= $selectedEffectivity === $date->effectivity_date ? 'selected' : ''; ?>><?= $esc(date('F j, Y', strtotime($date->effectivity_date))); ?></option><?php endforeach; ?></select></div><div class="col-auto"><button class="btn btn-light" type="submit">Filter</button></div></div></form></div></div>
        <?php if ($this->session->flashdata('success')): ?><div class="alert alert-success"><?= $esc($this->session->flashdata('success')); ?></div><?php endif; ?>
        <?php if ($this->session->flashdata('danger')): ?><div class="alert alert-danger"><?= $esc($this->session->flashdata('danger')); ?></div><?php endif; ?>
        <div class="card add-form mb-4"><div class="card-body"><h5 class="mb-3" id="formTitle">Add SWOT Entry</h5><form method="post" action="<?= base_url(); ?>Page/swot_save" id="swotForm"><input type="hidden" name="id" id="entryId"><div class="form-row"><div class="form-group col-md-2"><label>Year</label><input class="form-control" name="applicable_year" id="entryYear" value="<?= $esc($selectedYear); ?>" required></div><div class="form-group col-md-3"><label>Effectivity <span class="required">*</span></label><input class="form-control" type="date" name="effectivity_date" id="entryEffectivity" value="<?= $esc($selectedEffectivity ?: date('Y-m-d')); ?>" required></div><div class="form-group col-md-3"><label>Category <span class="required">*</span></label><select class="form-control" name="swot_type" id="entryType" required><option value="">Select category</option><?php foreach ($types as $type): ?><option value="<?= $type; ?>"><?= $type; ?></option><?php endforeach; ?></select></div><div class="form-group col-md-4"><label>Description <span class="required">*</span></label><textarea class="form-control" rows="2" name="description" id="entryDescription" required placeholder="Enter the SWOT item"></textarea></div></div><button class="btn btn-primary" type="submit" id="saveButton"><i class="mdi mdi-content-save"></i> Save Entry</button> <button class="btn btn-light d-none" type="button" id="cancelEdit">Cancel edit</button></form></div></div>
        <?php if (empty($grouped)): ?><div class="alert alert-light border">No SWOT entries found for this filter.</div><?php endif; ?>
        <?php foreach ($grouped as $effectivity => $effectivityEntries): ?><h5 class="mb-3"><i class="mdi mdi-calendar-check-outline mr-1"></i>Effective <?= $esc(date('F j, Y', strtotime($effectivity))); ?></h5><div class="row"><?php foreach ($types as $type): $style = $styles[$type]; ?><div class="col-xl-3 col-md-6 mb-4"><div class="card swot-card"><div class="card-header bg-<?= $style; ?> <?= $style === 'warning' ? 'text-dark' : 'text-white'; ?>"><i class="mdi mdi-<?= $type === 'Strength' ? 'arm-flex-outline' : ($type === 'Weakness' ? 'alert-outline' : ($type === 'Opportunity' ? 'lightbulb-outline' : 'shield-alert-outline')); ?> mr-1"></i><?= $type; ?>s</div><div class="card-body"><?php if (empty($effectivityEntries[$type])): ?><p class="text-muted mb-0">No <?= strtolower($type); ?>s recorded.</p><?php else: foreach ($effectivityEntries[$type] as $entry): ?><div class="swot-entry"><span class="entry-actions"><button type="button" class="edit-entry" title="Edit" data-id="<?= (int)$entry->id; ?>" data-year="<?= $esc($entry->applicable_year); ?>" data-effectivity="<?= $esc($entry->effectivity_date); ?>" data-type="<?= $esc($entry->swot_type); ?>" data-description="<?= $esc($entry->description); ?>"><i class="mdi mdi-pencil"></i></button><form method="post" action="<?= base_url(); ?>Page/swot_delete" class="d-inline"><input type="hidden" name="id" value="<?= (int)$entry->id; ?>"><input type="hidden" name="applicable_year" value="<?= $esc($selectedYear); ?>"><input type="hidden" name="effectivity_date" value="<?= $esc($selectedEffectivity); ?>"><button class="delete" title="Delete" onclick="return confirm('Delete this SWOT entry?');"><i class="mdi mdi-delete"></i></button></form></span><?= $esc($entry->description); ?></div><?php endforeach; endif; ?></div></div></div><?php endforeach; ?></div><?php endforeach; ?>
    </div></div><?php include('includes/footer.php'); ?></div></div>
    <script src="<?= base_url(); ?>assets/js/vendor.min.js"></script><script src="<?= base_url(); ?>assets/js/app.min.js"></script>
    <script>document.querySelectorAll('.edit-entry').forEach(function(button){button.addEventListener('click',function(){document.getElementById('entryId').value=this.dataset.id;document.getElementById('entryYear').value=this.dataset.year;document.getElementById('entryEffectivity').value=this.dataset.effectivity;document.getElementById('entryType').value=this.dataset.type;document.getElementById('entryDescription').value=this.dataset.description;document.getElementById('formTitle').textContent='Edit SWOT Entry';document.getElementById('saveButton').innerHTML='<i class="mdi mdi-content-save"></i> Update Entry';document.getElementById('cancelEdit').classList.remove('d-none');window.scrollTo({top:0,behavior:'smooth'});});});document.getElementById('cancelEdit').addEventListener('click',function(){document.getElementById('swotForm').reset();document.getElementById('entryId').value='';document.getElementById('entryYear').value='<?= $esc($selectedYear); ?>';document.getElementById('entryEffectivity').value='<?= $esc($selectedEffectivity ?: date('Y-m-d')); ?>';document.getElementById('formTitle').textContent='Add SWOT Entry';document.getElementById('saveButton').innerHTML='<i class="mdi mdi-content-save"></i> Save Entry';this.classList.add('d-none');});</script>
</body></html>
