<?php $esc = function($value) { return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8'); }; ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= $esc($title); ?> | SDO Davao Oriental</title>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@600;700&display=swap" rel="stylesheet">
    <style>
        :root { --navy:#102d4e; --blue:#1269aa; --aqua:#55c5c4; --gold:#f4bd4f; --muted:#64748b; --border:#e3eaf2; } *{box-sizing:border-box} body{margin:0;background:#f6f8fb;color:var(--navy);font-family:"DM Sans","Segoe UI",system-ui,sans-serif}.topline{height:5px;background:linear-gradient(90deg,var(--aqua),#388ec5 48%,var(--gold))}.shell{width:min(1050px,calc(100% - 32px));margin:auto}.nav{background:#fff;border-bottom:1px solid var(--border)}.nav-inner{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:17px 0}.brand{font:700 21px/1.1 "Playfair Display",Georgia,serif}.brand small{display:block;margin-bottom:3px;color:var(--blue);font:700 10px/1.3 "DM Sans",sans-serif;letter-spacing:.13em;text-transform:uppercase}.back{padding:10px 17px;border:1px solid var(--border);border-radius:999px;color:var(--navy);font-size:14px;font-weight:700;text-decoration:none}main{padding:38px 0 80px}.hero{padding:38px;border-radius:26px;color:#fff;background:linear-gradient(125deg,#102d4e,#155e96);box-shadow:0 24px 58px rgba(16,45,78,.18)}.eyebrow{margin:0 0 12px;color:#ffe09a;font-size:11px;font-weight:700;letter-spacing:.16em;text-transform:uppercase}h1{margin:0;font:700 clamp(1.8rem,4vw,2.65rem)/1.15 "Playfair Display",Georgia,serif}.hero p:last-child{margin:13px 0 0;color:rgba(255,255,255,.86);line-height:1.65}.panel{margin-top:20px;padding:12px;border:1px solid var(--border);border-radius:20px;background:#fff;box-shadow:0 16px 40px rgba(18,45,78,.07)}table{width:100%;border-collapse:collapse}th{padding:15px 14px;color:var(--blue);border-bottom:1px solid var(--border);font-size:11px;letter-spacing:.08em;text-align:left;text-transform:uppercase}td{padding:17px 14px;border-bottom:1px solid #edf1f5;color:var(--muted)}tr:last-child td{border-bottom:0}.empty{padding:42px;color:var(--muted);text-align:center}@media(max-width:700px){.nav-inner{align-items:flex-start;flex-direction:column}.hero{padding:30px 24px}.panel{overflow-x:auto}table{min-width:600px}}
    </style>
</head>
<body>
<div class="topline"></div><nav class="nav"><div class="shell nav-inner"><div class="brand"><small>Department of Education</small>SDO Davao Oriental</div><a class="back" href="<?= site_url('Page/partner_school_needs_list'); ?>">← All schools</a></div></nav>
<main class="shell"><section class="hero"><p class="eyebrow">School needs</p><h1><?= $esc($school->schoolName); ?></h1><p><?= $esc(trim(($school->brgy ?? '') . ', ' . ($school->city ?? '') . ', ' . ($school->province ?? ''))); ?></p></section><section class="panel"><table><thead><tr><th>#</th><th>Need / item</th><th>Quantity</th><th>Remarks</th><th>Date added</th></tr></thead><tbody><?php if (!empty($needs)): ?><?php foreach ($needs as $index => $need): ?><tr><td><?= (int) $index + 1; ?></td><td><?= $esc($need->need); ?></td><td><?= (int) $need->quantity; ?></td><td><?= $esc($need->remarks ?? '—'); ?></td><td><?= $esc($need->created_at); ?></td></tr><?php endforeach; ?><?php else: ?><tr><td class="empty" colspan="5">No needs recorded yet for this school.</td></tr><?php endif; ?></tbody></table></section></main>
</body>
</html>
